t0: 10
n_particles: 1000 # number of SMC particles (num of w points)
n_data: 1000 # number of SMC runs to draw data from
n_bins: 50 # number of bins
max_iters: 100 # maximum number of iterations before breaking
n_batch: 250 # number of points in a batch
directory: ./files
data_filename: data_t0_point_1

