t0: 10
n_particles: 1000 # number of SMC particles (num of w points)
max_iters: 100 # maximum number of iterations before breaking
n_runs: 1000
n_eff_thresh: 5e-5
directory: ./run_logs
result_path: lw