t0: 10
n_particles: 1000 # number of SMC particles (num of w points)
n_bins: 50 # number of bins
max_iters: 100 # maximum number of iterations before breaking
n_runs: 1000
n_eff_thresh: 5e-5
directory: ./run_logs
model_filename: model_500_250_50_t0_10.pt
results_filename: results_500_250_50_t0_10
model_neurons: [500, 250, 50]